/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package representation.planner;

import business.maintenanceactivity.Material;
import business.maintenanceactivity.Skill;
import business.user.Planner;
import exception.MaintenanceActivityException;
import exception.MaterialException;
import exception.SkillException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import persistence.maintenanceactivity.MaintenanceActivityDAOImpl;
import persistence.maintenanceactivity.RequiredMaterialForMaintenanceDAOImpl;
import persistence.maintenanceactivity.RequiredSkillForMaintenanceDAOImpl;
import persistence.maintenanceactivity.SiteDaoImpl;

/**
 *
 * @author aless
 */
public class CreateActivity extends javax.swing.JFrame {
    private Planner planner = null;
    private final JTextField[] textFields = new JTextField[8];
    private boolean interruptible = false;
    private boolean typeOfActivity = false;
    private MyDocumentListener myDocumentListener = null;
    /**
     * Creates new form CreateActivity
     * @param planner
     */
    public CreateActivity(Planner planner) {
        this.planner = planner;
        initComponents();
        myDocumentListener = new MyDocumentListener();
        textFields[0] = jActivityId;
        textFields[1] = jBranchOffice;
        textFields[2] = jArea;
        textFields[3] = jTypology;
        textFields[4] = jActivityDescription;
        textFields[5] = jEstimatedInterventionTime;
        textFields[6] = jDate;
        textFields[7] = jMaterials;
        for (int i = 0; i<textFields.length-1;i++) {
            textFields[i].getDocument().addDocumentListener(myDocumentListener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTypeOfActivity = new javax.swing.ButtonGroup();
        buttonGroupInterruptible = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jActivityId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBranchOffice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTypology = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jActivityDescription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEstimatedInterventionTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMaterials = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPlanned = new javax.swing.JRadioButton();
        jExtra = new javax.swing.JRadioButton();
        jEwo = new javax.swing.JRadioButton();
        jCreate = new javax.swing.JButton();
        jInterruptibleTrue = new javax.swing.JRadioButton();
        jInterruptibleFalse = new javax.swing.JRadioButton();
        jErrorActivityId = new javax.swing.JLabel();
        jErrorEstimatedInterventionTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ActivityID: ");

        jActivityId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jActivityIdKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Branch Office:");

        jBranchOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBranchOfficeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Area:");

        jArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Typology:");

        jTypology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypologyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Activity Description:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estimated Intervention Time:");
        jLabel7.setToolTipText("");

        jEstimatedInterventionTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEstimatedInterventionTimeKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date (YYYY-MM-DD):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Materials (separate each material with comma):");

        jMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaterialsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Interruptible Activity:");

        jPlanned.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jPlanned);
        jPlanned.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPlanned.setText("Planned Activity");
        jPlanned.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jPlannedItemStateChanged(evt);
            }
        });
        jPlanned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlannedActionPerformed(evt);
            }
        });

        jExtra.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jExtra);
        jExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jExtra.setText("Extra Activity");
        jExtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jExtraItemStateChanged(evt);
            }
        });

        jEwo.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jEwo);
        jEwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEwo.setText("EWO");
        jEwo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jEwoItemStateChanged(evt);
            }
        });

        jCreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCreate.setText("Create Activity");
        jCreate.setEnabled(false);
        jCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateActionPerformed(evt);
            }
        });

        jInterruptibleTrue.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupInterruptible.add(jInterruptibleTrue);
        jInterruptibleTrue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInterruptibleTrue.setText("True");
        jInterruptibleTrue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jInterruptibleTrueItemStateChanged(evt);
            }
        });

        jInterruptibleFalse.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupInterruptible.add(jInterruptibleFalse);
        jInterruptibleFalse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInterruptibleFalse.setText("False");
        jInterruptibleFalse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jInterruptibleFalseItemStateChanged(evt);
            }
        });

        jErrorActivityId.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jErrorEstimatedInterventionTime.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jActivityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jActivityId))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBranchOffice)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTypology, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jErrorActivityId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jMaterials))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jErrorEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(jInterruptibleTrue)
                                .addGap(18, 18, 18)
                                .addComponent(jInterruptibleFalse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPlanned)
                                .addGap(18, 18, 18)
                                .addComponent(jExtra)
                                .addGap(18, 18, 18)
                                .addComponent(jEwo)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActivityId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jErrorActivityId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBranchOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTypology, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jActivityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jErrorEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInterruptibleTrue)
                    .addComponent(jInterruptibleFalse))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlanned)
                    .addComponent(jExtra)
                    .addComponent(jEwo))
                .addGap(40, 40, 40)
                .addComponent(jCreate)
                .addGap(22, 22, 22))
        );

        jActivityId.getAccessibleContext().setAccessibleName("");
        jPlanned.getAccessibleContext().setAccessibleName("Planned");
        jEwo.getAccessibleContext().setAccessibleName("Ewo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPlannedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlannedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlannedActionPerformed

    private void jBranchOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBranchOfficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBranchOfficeActionPerformed

    private void jMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaterialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaterialsActionPerformed

    private void jInterruptibleTrueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jInterruptibleTrueItemStateChanged
        interruptible = true;
        checkFields();
    }//GEN-LAST:event_jInterruptibleTrueItemStateChanged

    private void jInterruptibleFalseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jInterruptibleFalseItemStateChanged
        interruptible = true;
        checkFields();
    }//GEN-LAST:event_jInterruptibleFalseItemStateChanged

    private void jPlannedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jPlannedItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jPlannedItemStateChanged

    private void jExtraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jExtraItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jExtraItemStateChanged

    private void jEwoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jEwoItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jEwoItemStateChanged

    private void jCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateActionPerformed
        try {
            int activityId = Integer.parseInt(jActivityId.getText());
            String branchOffice = jBranchOffice.getText();
            String area = jArea.getText();
            String typology = jTypology.getText();
            String activityDescription = jActivityDescription.getText();
            int estimatedInterventionTime = Integer.parseInt(jEstimatedInterventionTime.getText());
            String date = jDate.getText();
            
            LinkedList<Material> materials = new LinkedList<>();
            LinkedList<Skill> skills = new LinkedList<>();
            String materialString = jMaterials.getText();
            if (!materialString.equals("")){
                String[] materialStringList = materialString.split(",");
                for (String material : materialStringList)
                    materials.add(new Material(material.trim()));
            }else materials = null;
            boolean interruptibleActivity;
            interruptibleActivity = jInterruptibleTrue.isSelected();
            boolean plannedActivity = jPlanned.isSelected();
            boolean extraActivity = jExtra.isSelected();
            boolean ewo = jEwo.isSelected();
            planner.makeMaintenanceActivity(activityId, branchOffice, area, "", typology, activityDescription, estimatedInterventionTime, date, " ", materials, interruptibleActivity, plannedActivity, extraActivity, ewo);
            jActivityId.setText("");
            jBranchOffice.setText("");
            jArea.setText("");
            jTypology.setText("");
            jActivityDescription.setText("");
            jEstimatedInterventionTime.setText("");
            jDate.setText("");
            jMaterials.setText("");
            buttonGroupInterruptible.clearSelection();
            buttonGroupTypeOfActivity.clearSelection();
            jCreate.setEnabled(false);
        } catch (MaintenanceActivityException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting into MaintenanceActivity table", "ERRORE", JOptionPane.ERROR_MESSAGE);
        } catch (MaterialException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting into RequiredMaterial table", "ERRORE", JOptionPane.ERROR_MESSAGE);
        } catch (SkillException ex) {
            JOptionPane.showMessageDialog(this, "Error inserting into RequiredProcedureSkill table", "ERRORE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCreateActionPerformed

    private void jActivityIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jActivityIdKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jActivityId.setEditable(false);
            jErrorActivityId.setText("Enter digits only!");
        }else {
            jActivityId.setEditable(true);
            jErrorActivityId.setText("");
        }
    }//GEN-LAST:event_jActivityIdKeyPressed

    private void jEstimatedInterventionTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEstimatedInterventionTimeKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jEstimatedInterventionTime.setEditable(false);
            jErrorEstimatedInterventionTime.setText("Enter digits only!");
        }else {
            jEstimatedInterventionTime.setEditable(true);
            jErrorEstimatedInterventionTime.setText("");
        }
    }//GEN-LAST:event_jEstimatedInterventionTimeKeyPressed

    private void jAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAreaActionPerformed

    private void jTypologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypologyActionPerformed

    private class MyDocumentListener implements DocumentListener {

        @Override
        public void changedUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        // if any changes to any document (any of the above methods called)
        // check if all JTextfields have text. If so, activate the action
        public boolean checkTextFields() {
            boolean allFieldsHaveText = true;
            for (int i = 0; i<textFields.length-1;i++) {
                if (textFields[i].getText().trim().isEmpty()) {
                    allFieldsHaveText = false;
                }
            }
            return allFieldsHaveText;
        }

    }
    
    private void checkFields(){
        if (interruptible && typeOfActivity && myDocumentListener.checkTextFields()){
            jCreate.setEnabled(true);
        }else jCreate.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Planner planner = new Planner("admin","admin", new MaintenanceActivityDAOImpl(new SiteDaoImpl()),
                new RequiredMaterialForMaintenanceDAOImpl());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateActivity(planner).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInterruptible;
    private javax.swing.ButtonGroup buttonGroupTypeOfActivity;
    private javax.swing.JTextField jActivityDescription;
    private javax.swing.JTextField jActivityId;
    private javax.swing.JTextField jArea;
    private javax.swing.JTextField jBranchOffice;
    private javax.swing.JButton jCreate;
    private javax.swing.JTextField jDate;
    private javax.swing.JLabel jErrorActivityId;
    private javax.swing.JLabel jErrorEstimatedInterventionTime;
    private javax.swing.JTextField jEstimatedInterventionTime;
    private javax.swing.JRadioButton jEwo;
    private javax.swing.JRadioButton jExtra;
    private javax.swing.JRadioButton jInterruptibleFalse;
    private javax.swing.JRadioButton jInterruptibleTrue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jMaterials;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPlanned;
    private javax.swing.JTextField jTypology;
    // End of variables declaration//GEN-END:variables
}
