/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package representation.planner;

import business.maintenanceactivity.MaintenanceProcedure;
import business.maintenanceactivity.Material;
import business.user.Planner;
import java.time.LocalDate;
import java.util.LinkedList;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author aless
 */
public class CreateActivity extends javax.swing.JFrame {
    private Planner planner = null;
    private final JTextField[] textFields = new JTextField[10];
    private boolean interruptible = false;
    private boolean typeOfActivity = false;
    private MyDocumentListener myDocumentListener = null;
    /**
     * Creates new form CreateActivity
     * @param planner
     */
    public CreateActivity(Planner planner) {
        this.planner = planner;
        initComponents();
        myDocumentListener = new MyDocumentListener();
        textFields[0] = jActivityId;
        textFields[1] = jBranchOffice;
        textFields[2] = jArea;
        textFields[3] = jWorkspaceNotes;
        textFields[4] = jTypology;
        textFields[5] = jActivityDescription;
        textFields[6] = jEstimatedInterventionTime;
        textFields[7] = jDate;
        textFields[8] = jMaintenanceProcedure;
        textFields[9] = jMaterials;
        for (JTextField textField : textFields) {
            textField.getDocument().addDocumentListener(myDocumentListener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTypeOfActivity = new javax.swing.ButtonGroup();
        buttonGroupInterruptible = new javax.swing.ButtonGroup();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jActivityId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBranchOffice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jWorkspaceNotes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTypology = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jActivityDescription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jEstimatedInterventionTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMaintenanceProcedure = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMaterials = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPlanned = new javax.swing.JRadioButton();
        jExtra = new javax.swing.JRadioButton();
        jEwo = new javax.swing.JRadioButton();
        jCreate = new javax.swing.JButton();
        jInterruptibleTrue = new javax.swing.JRadioButton();
        jInterruptibleFalse = new javax.swing.JRadioButton();
        jErrorActivityId = new javax.swing.JLabel();
        jErrorEstimatedInterventionTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ActivityID: ");

        jActivityId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jActivityIdKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Branch Office:");

        jBranchOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBranchOfficeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Area:");

        jArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Workspace Notes:");

        jWorkspaceNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWorkspaceNotesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Typology:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Activity Description:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estimated Intervention Time:");
        jLabel7.setToolTipText("");

        jEstimatedInterventionTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEstimatedInterventionTimeKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date (YYYY-MM-DD):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Maintenance Procedure:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Materials (separate each material with comma):");

        jMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaterialsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Interruptible Activity:");

        jPlanned.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jPlanned);
        jPlanned.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPlanned.setText("Planned Activity");
        jPlanned.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jPlannedItemStateChanged(evt);
            }
        });
        jPlanned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlannedActionPerformed(evt);
            }
        });

        jExtra.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jExtra);
        jExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jExtra.setText("Extra Activity");
        jExtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jExtraItemStateChanged(evt);
            }
        });

        jEwo.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupTypeOfActivity.add(jEwo);
        jEwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEwo.setText("EWO");
        jEwo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jEwoItemStateChanged(evt);
            }
        });

        jCreate.setBackground(new java.awt.Color(102, 102, 102));
        jCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCreate.setForeground(new java.awt.Color(255, 255, 255));
        jCreate.setText("Create Activity");
        jCreate.setEnabled(false);
        jCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateActionPerformed(evt);
            }
        });

        jInterruptibleTrue.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupInterruptible.add(jInterruptibleTrue);
        jInterruptibleTrue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInterruptibleTrue.setText("True");
        jInterruptibleTrue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jInterruptibleTrueItemStateChanged(evt);
            }
        });

        jInterruptibleFalse.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroupInterruptible.add(jInterruptibleFalse);
        jInterruptibleFalse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInterruptibleFalse.setText("False");
        jInterruptibleFalse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jInterruptibleFalseItemStateChanged(evt);
            }
        });

        jErrorActivityId.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jErrorEstimatedInterventionTime.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMaintenanceProcedure))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEstimatedInterventionTime))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jActivityDescription))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTypology))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jArea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jActivityId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBranchOffice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWorkspaceNotes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPlanned)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jInterruptibleTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jInterruptibleFalse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jExtra)
                                .addGap(18, 18, 18)
                                .addComponent(jEwo)))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jErrorActivityId, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jErrorEstimatedInterventionTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActivityId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jErrorActivityId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBranchOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWorkspaceNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTypology, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jActivityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jErrorEstimatedInterventionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jMaintenanceProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInterruptibleTrue)
                    .addComponent(jInterruptibleFalse))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlanned)
                    .addComponent(jExtra)
                    .addComponent(jEwo))
                .addGap(86, 86, 86)
                .addComponent(jCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jActivityId.getAccessibleContext().setAccessibleName("");
        jPlanned.getAccessibleContext().setAccessibleName("Planned");
        jEwo.getAccessibleContext().setAccessibleName("Ewo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPlannedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlannedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlannedActionPerformed

    private void jWorkspaceNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWorkspaceNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWorkspaceNotesActionPerformed

    private void jBranchOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBranchOfficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBranchOfficeActionPerformed

    private void jMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaterialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaterialsActionPerformed

    private void jInterruptibleTrueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jInterruptibleTrueItemStateChanged
        interruptible = true;
        checkFields();
    }//GEN-LAST:event_jInterruptibleTrueItemStateChanged

    private void jInterruptibleFalseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jInterruptibleFalseItemStateChanged
        interruptible = true;
        checkFields();
    }//GEN-LAST:event_jInterruptibleFalseItemStateChanged

    private void jPlannedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jPlannedItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jPlannedItemStateChanged

    private void jExtraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jExtraItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jExtraItemStateChanged

    private void jEwoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jEwoItemStateChanged
        typeOfActivity = true;
        checkFields();
    }//GEN-LAST:event_jEwoItemStateChanged

    private void jCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateActionPerformed
        int activityId = Integer.parseInt(jActivityId.getText());
        String branchOffice = jBranchOffice.getText();
        String area = jArea.getText();
        String workspaceNotes = jWorkspaceNotes.getText();
        String typology = jTypology.getText();
        String activityDescription = jActivityDescription.getText();
        int estimatedInterventionTime = Integer.parseInt(jEstimatedInterventionTime.getText());
        String date = jDate.getText();
        String maintenanceProcedure = jMaintenanceProcedure.getText();
        LinkedList<Material> materials = new LinkedList<>();
        String materialString = jMaterials.getText();
        String[] materialStringList = materialString.split(",");
        for (String material : materialStringList)
            materials.add(new Material(material));
        boolean interruptibleActivity;
        if (jInterruptibleTrue.isSelected())
            interruptibleActivity = true;
        else
            interruptibleActivity = false;
        boolean plannedActivity = jPlanned.isSelected();
        boolean extraActivity = jExtra.isSelected();
        boolean ewo = jEwo.isSelected();
        boolean insert = planner.makeMaintenanceActivity(activityId, branchOffice, area, workspaceNotes, typology, activityDescription, estimatedInterventionTime, date, maintenanceProcedure, materials, interruptibleActivity, plannedActivity, extraActivity, ewo);
        if (!insert)
            System.out.println("Errore nell'inserimento");
        jActivityId.setText("");
        jBranchOffice.setText("");
        jArea.setText("");
        jWorkspaceNotes.setText("");
        jTypology.setText("");
        jActivityDescription.setText("");
        jEstimatedInterventionTime.setText("");
        jDate.setText("");
        jMaintenanceProcedure.setText("");
        jMaterials.setText("");
        buttonGroupInterruptible.clearSelection();
        buttonGroupTypeOfActivity.clearSelection();
        jCreate.setEnabled(false);
    }//GEN-LAST:event_jCreateActionPerformed

    private void jActivityIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jActivityIdKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jActivityId.setEditable(false);
            jErrorActivityId.setText("Enter digits only!");
        }else {
            jActivityId.setEditable(true);
            jErrorActivityId.setText("");
        }
    }//GEN-LAST:event_jActivityIdKeyPressed

    private void jEstimatedInterventionTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEstimatedInterventionTimeKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jEstimatedInterventionTime.setEditable(false);
            jErrorEstimatedInterventionTime.setText("Enter digits only!");
        }else {
            jEstimatedInterventionTime.setEditable(true);
            jErrorEstimatedInterventionTime.setText("");
        }
    }//GEN-LAST:event_jEstimatedInterventionTimeKeyPressed

    private void jAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAreaActionPerformed

    private class MyDocumentListener implements DocumentListener {

        @Override
        public void changedUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            checkTextFields();
            checkFields();
        }

        // if any changes to any document (any of the above methods called)
        // check if all JTextfields have text. If so, activate the action
        public boolean checkTextFields() {
            boolean allFieldsHaveText = true;
            for (JTextField jTextField : textFields) {
                if (jTextField.getText().trim().isEmpty()) {
                    allFieldsHaveText = false;
                }
            }
            return allFieldsHaveText;
        }

    }
    
    private void checkFields(){
        if (interruptible && typeOfActivity && myDocumentListener.checkTextFields()){
            jCreate.setEnabled(true);
        }else jCreate.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Planner planner = new Planner("User","pwd");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateActivity(planner).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInterruptible;
    private javax.swing.ButtonGroup buttonGroupTypeOfActivity;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField jActivityDescription;
    private javax.swing.JTextField jActivityId;
    private javax.swing.JTextField jArea;
    private javax.swing.JTextField jBranchOffice;
    private javax.swing.JButton jCreate;
    private javax.swing.JTextField jDate;
    private javax.swing.JLabel jErrorActivityId;
    private javax.swing.JLabel jErrorEstimatedInterventionTime;
    private javax.swing.JTextField jEstimatedInterventionTime;
    private javax.swing.JRadioButton jEwo;
    private javax.swing.JRadioButton jExtra;
    private javax.swing.JRadioButton jInterruptibleFalse;
    private javax.swing.JRadioButton jInterruptibleTrue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaintenanceProcedure;
    private javax.swing.JTextField jMaterials;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPlanned;
    private javax.swing.JTextField jTypology;
    private javax.swing.JTextField jWorkspaceNotes;
    // End of variables declaration//GEN-END:variables
}
