/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package representation.planner;

import business.maintenanceactivity.MaintenanceActivity;
import business.user.Planner;
import business.user.WeekConverter;
import exception.MaintenanceActivityException;
import exception.NotValidParameterException;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import presentation.manager.MessageManager;

/**
 *
 * @author gorra
 */
public class SelectionActivityGUI extends javax.swing.JFrame {
    private List<MaintenanceActivity> list;
    private Planner planner = null;
    private final DefaultTableModel tableModel;
    
    
    /**
     * Creates new form SelectionActivityGUI
     * @param planner
     */
    public SelectionActivityGUI(Planner planner) {
        this.planner = planner;
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) maintenanceActivityTable.getModel();
        inizializeField();    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        weekComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintenanceActivityTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selection Activity");

        jPanel1.setBackground(new java.awt.Color(187, 187, 100));
        jPanel1.setForeground(new java.awt.Color(187, 187, 100));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Week n°:");

        weekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        int numberOfWeeks = WeekConverter.getNumberOfWeeksInYear(LocalDate.now());
        for(int i=1;i<=numberOfWeeks;i++){
            weekComboBox.addItem(i);
        }
        weekComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekComboBoxActionPerformed(evt);
            }
        });

        maintenanceActivityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AREA", "TYPOLOGY", "<html>Estimated Intervention<br>Time [min]<html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        maintenanceActivityTable.setAutoscrolls(false);
        jScrollPane1.setViewportView(maintenanceActivityTable);
        maintenanceActivityTable.getTableHeader().setPreferredSize(new Dimension((int) maintenanceActivityTable.getSize().getWidth(), 40));
        if (maintenanceActivityTable.getColumnModel().getColumnCount() > 0) {
            maintenanceActivityTable.getColumnModel().getColumn(0).setMinWidth(40);
            maintenanceActivityTable.getColumnModel().getColumn(1).setMinWidth(200);
            maintenanceActivityTable.getColumnModel().getColumn(2).setMinWidth(200);
            maintenanceActivityTable.getColumnModel().getColumn(3).setMinWidth(150);
        }
        maintenanceActivityTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("SELECT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[] row = maintenanceActivityTable.getSelectedRows();
        if(row.length<=0){
            MessageManager.infoMessage(this,"No row selected");
        }else if(row.length > 1){
            MessageManager.infoMessage(this,"Select one row!");
        }else{
            VerifyActivity verifyActivity = new VerifyActivity(list.get(row[0]), planner);
            verifyActivity.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * Populates the table passing the number 
     * of the week (choosed from ComboBox) and 
     * the year for that week
     * @param evt 
     */
    private void weekComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekComboBoxActionPerformed
        LocalDate date = LocalDate.now();
        populateTable(weekComboBox.getSelectedIndex()+1, WeekConverter.getYear(date));
    }//GEN-LAST:event_weekComboBoxActionPerformed


    /**
     * This method initializes all fields of the GUI.
     */
    private void inizializeField() {
        LocalDate date = LocalDate.now();
        int weekNumber = WeekConverter.getWeek(date);
        int year = WeekConverter.getYear(date);
        weekComboBox.setSelectedIndex(weekNumber-1);
        populateTable(weekNumber, year);
    }
    
    
    /**
     * This method populates the table based on
     * the week and the year for that week
     * @param weekNumber number of a week
     * @param year year
     */
    public void populateTable(int weekNumber, int year){
        tableModel.setRowCount(0);
        try {
            list = planner.viewMaintenanceActivityByWeek(weekNumber, year);
            for (MaintenanceActivity ma : list) {
                tableModel.addRow(new Object[]{ma.getActivityId(), ma.getSite().getArea(),
                   ma.getTypology(), ma.getEstimatedInterventionTime()});
            }
        } catch (MaintenanceActivityException | NotValidParameterException ex) {
            MessageManager.errorMessage(this,ex.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintenanceActivityTable;
    private javax.swing.JComboBox<Integer> weekComboBox;
    // End of variables declaration//GEN-END:variables
}
