/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.administrator;


import business.user.SystemAdministrator;
import business.user.UserRole;
import dto.MaintainerDTO;
import dto.PlannerDTO;
import dto.SystemAdministratorDTO;
import dto.UserDTO;
import exception.NotValidParameterException;
import exception.UsersException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import presentation.manager.MessageManager;

/**
 *
 * @author gorra
 */
public class ModifyUser extends javax.swing.JDialog {
    private String oldUsername;
    private String oldPassword;
    private String oldRole;
    private final DefaultTableModel tableModel;
    private final int tableIndex;
    private SystemAdministrator administrator;
    

    /**
     * 
     * @param parent
     * @param modal
     * @param username
     * @param password
     * @param role
     * @param tableModel 
     */
    public ModifyUser(java.awt.Frame parent, boolean modal, String username, 
            String password, String role, DefaultTableModel tableModel, 
            int tableIndex, SystemAdministrator administrator) {
        super(parent, modal);
        this.oldUsername = username;
        this.oldPassword = password;
        this.oldRole = role;
        this.tableModel = tableModel;
        this.tableIndex = tableIndex;
        this.administrator = administrator;
        initComponents();
        inizializeField(username, password, role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        roleComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(187, 187, 100));
        jPanel2.setForeground(new java.awt.Color(187, 187, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 400));

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");

        roleLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        roleLabel.setText("Role:");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(UserRole.values()));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(usernameLabel))
                    .addComponent(roleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 95, Short.MAX_VALUE)
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleComboBox)
                    .addComponent(roleLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * When the designated button is pressed the administrator
     * can decide whether to discard all changes
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int result = MessageManager.confirmRequest(this,"Are you sure? All modifies will be lost", "CANCEL");
        if (result == EXIT_ON_CLOSE)
            this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    /**
     * When the designated button is pressed the 
     * administrator can decide to modify the user
     * @param evt 
     */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        int result = MessageManager.confirmRequest(this,"Are you sure you want to modify this user?", "CONFIRM");
        if (result == EXIT_ON_CLOSE) {
            try {
                String newUsername = usernameTextField.getText();
                String newPassword = passwordTextField.getText();
                String newRole = String.valueOf(roleComboBox.getSelectedItem());

                if (checkIfModified(oldUsername, oldPassword, oldRole, newUsername, newPassword, newRole)) {
                   if (administrator.modifyUser(oldUsername, makeUser(newUsername, newPassword, newRole))) {
                        tableModel.setValueAt(newUsername, tableIndex, 0);
                        tableModel.setValueAt(newPassword, tableIndex, 1);
                        tableModel.setValueAt(newRole, tableIndex, 2);
                    }
                }
            } catch (UsersException | NotValidParameterException ex) {
                JOptionPane.showMessageDialog(this, "Error while trying to modify this user", "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed


    /**
     * This method allows to inizialize all fields in the GUI
     * @param username username of the user to set in the text field
     * @param password password of the user to set in the text field
     * @param role role of the user to set in the comboBox
     */
    private void inizializeField(String username, String password, String role){
        usernameTextField.setText(username);
        passwordTextField.setText(password);
        roleComboBox.setSelectedItem(UserRole.valueOf(role));
    }    
    
    
    /**
     * This method allows you to create the right
     * data transfer object for the user
     * @param newUsername new username of the user
     * @param newPassword new password of the user
     * @param newRole new role of the user
     * @return {@code UserDTO}
     */
    private UserDTO makeUser(String newUsername, String newPassword, String newRole){
        if (newRole.equals(UserRole.PLANNER.toString())){
            return new PlannerDTO(newUsername, newPassword);
        }
        else if (newRole.equals(UserRole.MAINTAINER.toString())){
            return new MaintainerDTO(newUsername, newPassword);
        }
        else{ 
            return new SystemAdministratorDTO(newUsername, newPassword);
        } 
    }
    
    

    /**
     * This method checks if the user information has changed
     * @param oldUsername old usernme of the user 
     * @param oldPassword old password of the user
     * @param oldRole old role of the user
     * @param newUsername new username of the user
     * @param newPassword new password of the user 
     * @param newRole new role of the user
     * @return {@code true} if the user is modified,
     * {@code false} otherwise
     */
    private boolean checkIfModified(String oldUsername, String oldPassword, String oldRole, String newUsername, String newPassword, String newRole) {
        return !(oldUsername.equals(newUsername)
                && oldPassword.equals(newPassword)
                && oldRole.equals(newRole));
    }
    
    

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModifyUser dialog = new ModifyUser(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<UserRole> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
